name: contapp
description: Um aplicativo de lista de contatos intuitivo e fácil de usar. Ele permite que você gerencie seus contatos de maneira eficiente. Você pode adicionar, editar e excluir contatos facilmente. Ele também oferece recursos como pesquisa rápida.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  parse_server_sdk_flutter: ^3.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

